export const typographyColorList = [
  'primary',
  'secondary',
  'disabled',
  'inverse',
  'branded',
  'onbranded',
  'danger',
  'ondanger',
  'success',
  'onsuccess',
  'info',
  'oninfo',
  'onwarning',
  'onneutral',
] as const;

export const typographyVariantList = [
  'display3XLarge',
  'display2XLarge',
  'displayXLarge',
  'displayLarge',
  'displayMedium',
  'displaySmall',
  'displayXSmall',
  'display2XSmall',
  'subtitle2XLarge',
  'subtitleXLarge',
  'subtitleLarge',
  'subtitleMedium',
  'subtitleSmall',
  'bodyLarge',
  'bodyMedium',
  'bodySmall',
  'labelLarge',
  'labelMedium',
  'labelSmall',
  'caption',
] as const;

// for a11y users should pass proper aria attributes when used with non semantic html tags as `div` or `span`.
// exapmple: <Typography as={'div'} variant={'bodyMedium'} role="heading" aria-level={3}>
export const typographyElementList = [
  'div',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'legend',
  'p',
  'span',
  'strong',
  'b',
  'i',
  'em',
  'small',
  'sub',
  'sup',
  'del',
  'ins',
  'mark',
  'article',
  'q',
  'blockquote',
  'abbr',
  'address',
] as const;

export const deprecatedHeadings = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as const;
